1.Web/Controllers/BlogController.cs
using System;
using BLL.Services.Interfaces;
using Core.Models.DTO.Blogs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Web.Services.Interfaces;

namespace Web.Controllers
{
    public class BlogController : Controller
    {
        private readonly ILogger<BlogController> _logger;
        private readonly IUserService _userService;
        private readonly IBlogService _blogService;

        public BlogController(ILogger<BlogController> logger, IUserService userService, IBlogService blogService)
        {
            _logger = logger;
            _userService = userService;
            _blogService = blogService;
        }

        public IActionResult Index()
        {
            string userName = User.Identity.Name;
            if (userName == null)
            {
                return View();
            }
            string userId = _userService.GetUserByNameAsync(userName).Result.Id;
            IndexModel model = _blogService.GetIndexModel(userId);
            return View(model);
        }

        [HttpGet("/user/{urlUserName}/blog")]
        public IActionResult Index(string urlUserName)
        {
            string userName = User.Identity.Name;
            if (userName != urlUserName)
            {
                _logger.LogInformation($"使用者(userName:{userName}) 嘗試進入 /user/{urlUserName}/blog 頁面。回傳「無法瀏覽」。");
                throw new Exception("無法瀏覽這個頁面，不便之處，敬請見諒。");
            }
            string userId = _userService.GetUserByNameAsync(urlUserName).Result.Id;
            IndexModel model = _blogService.GetIndexModel(userId);
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CreateModel model)
        {
            string userName = User.Identity.Name;
            string userId = _userService.GetUserByNameAsync(userName).Result.Id;

            if (ModelState.IsValid)
            {
                _blogService.Create(model, userId);
            }

            return RedirectToAction("Details", new { urlUserName = userName, blogId = model.Id });
        }

        [HttpGet("user/{urlUserName}/blog/{blogId}")]
        public IActionResult Details(string urlUserName, int blogId)
        {
            string userName = User.Identity.Name;
            if (urlUserName != userName)
            {
                return Unauthorized($"錯誤: 登入者({userName}) 試圖訪問 {urlUserName} 的資訊");
            }
            string userId = _userService.GetUserByNameAsync(userName).Result.Id;

            DetailsModel model = _blogService.GetDetails(blogId, userId);
            return View(model);
        }

        [HttpGet("user/{urlUserName}/blog/{blogId}/edit")]
        public IActionResult Edit(string urlUserName, int blogId)
        {
            string userName = User.Identity.Name;
            if (urlUserName != userName)
            {
                return Unauthorized($"錯誤: 登入者({userName}) 試圖訪問 {urlUserName} 的資訊");
            }
            string userId = _userService.GetUserByNameAsync(userName).Result.Id;

            EditModel model = _blogService.GetEditModel(blogId, userId);
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(EditModel model)
        {
            string userName = User.Identity.Name;
            string userId = _userService.GetUserByNameAsync(userName).Result.Id;

            if (ModelState.IsValid)
            {
                _blogService.Edit(model, userId);
            }

            return RedirectToAction("Details", new { urlUserName = userName, blogId = model.Id });
        }

        [HttpPost]
        public IActionResult Delete(string urlUserName, int blogId)
        {
            string userName = User.Identity.Name;
            if (urlUserName != userName)
            {
                return Unauthorized($"錯誤: 登入者({userName}) 試圖訪問 {urlUserName} 的資訊");
            }

            _blogService.Delete(blogId);

            return RedirectToAction("Index", new { urlUserName = userName });
        }
    }
}

1.Web/Views/Blog/Create.cshtml
@using Core.Models.DTO.Blogs;
@model CreateModel

<p class="text-center py-2">新增Blog</p>
<div class="row">
    <div class="col-xl-4 col-md-2"></div>
    <div class="col-xl-4 col-md-8 col-xs-12">
        <div class="wrapper">
            <div class="block-center mt-4 wd-xl">
                <!-- START card-->
                <div class="card card-flat">
                    <div class="card-body">
                        <form method="post" class="mb-3">
                            <div asp-validation-summary="All" class="text-danger"></div>
                            <div class="form-group">
                                <div class="input-group with-focus">
                                    @Html.TextBoxFor(m => m.CoverImageUrl, new { @class = "form-control", placeholder = @Html.DisplayNameFor(m => m.CoverImageUrl) })
                                </div>
                                <span asp-validation-for="CoverImageUrl" class="form-text text-danger"></span>
                            </div>
                            <div class="form-group">
                                <div class="input-group">
                                    @Html.TextBoxFor(m => m.Title, new { @class = "form-control", placeholder = @Html.DisplayNameFor(m => m.Title) })
                                </div>
                                <span asp-validation-for="Title" class="form-text text-danger"></span>
                            </div>

                            <div class="form-group">
                                <div class="input-group">
                                    @Html.TextBoxFor(m => m.Content, new { @class = "form-control", placeholder = @Html.DisplayNameFor(m => m.Content) })
                                </div>
                                <span asp-validation-for="Content" class="form-text text-danger"></span>
                            </div>

                            <button class="btn btn-block btn-primary mt-3" type="submit">儲存文章</button>
                        </form>
                    </div>
                </div>
                <!-- END card-->
            </div>
        </div>
    </div>
    <div class="col-xl-4 col-md-2"></div>
</div>

1.Web/Views/Blog/Details.cshtml
@model Core.Models.DTO.Blogs.DetailsModel

<div class="row">
    <div class="col-xl-2 col-md-2"></div>
    <div class="col-xl-8 col-md-8 col-xs-12">
        <div class="wrapper">
            <div class="block-center mt-4 wd-xl">
                <!-- START card-->
                <div class="card card-flat">
                    <div class="card-body">
                        <img class="img-fluid" src="@Model.CoverImageUrl" alt="@Model.CoverImageUrl">
                        <div class="card-body">
                            <p>
                                <span>
                                    <small class="mr-1">@Model.UpdateTime</small>
                                </span>
                            </p>
                            <h4>@Model.Title</h4>
                            <p>@Model.Content</p>
                        </div>
                        <a href="/user/@User.Identity.Name/blog/@Model.Id/edit" class="nav-link text-dark">編輯文章</a>
                        <form method="post" action="/blog/delete">
                            <input type="hidden" name="blogId" value="@Model.Id">
                            <input type="hidden" name="urlUserName" value="@User.Identity.Name">
                            <button class="btn btn-block btn-primary mt-3" type="submit">刪除文章</button>
                        </form>
                    </div>
                </div>
                <!-- END card-->
            </div>
        </div>
    </div>
    <div class="col-xl-2 col-md-2"></div>
</div>

1.Web/Views/Blog/Edit.cshtml
@model Core.Models.DTO.Blogs.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>EditModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" class="mb-3" action="/blog/edit">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="hidden" name="id" id="blogId" value="@Model.Id">
            <div class="form-group">
                <label asp-for="CoverImageUrl" class="control-label"></label>
                <input asp-for="CoverImageUrl" class="form-control" />
                <span asp-validation-for="CoverImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <button class="btn btn-block btn-primary mt-3" type="submit">儲存文章</button>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

1.Web/Views/Blog/Index.cshtml
@using Core.Models.DTO.Blogs
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

@model IndexModel;

@section Styles{
    <!-- JQCLOUD-->
    <link rel="stylesheet" href="/vendor/jqcloud2/dist/jqcloud.css">
}

@if (SignInManager.IsSignedIn(User)){
    <a asp-area="" asp-controller="Blog" asp-action="Create">寫新文章</a>

    <div class="content-wrapper">
        <div class="row">
            <!-- Blog Content-->
            <div class="col-xl-9">
                <div class="card-columns">
                    @*文章卡*@
                    @foreach (IndexModel.Blog blog in Model.Blogs)
                    {
                        @*文章卡*@
                        <div class="card">
                            @*封面*@
                            <a href="/user/@User.Identity.Name/blog/@blog.Id">
                                <img class="img-fluid" src="@blog.CoverImageUrl" alt="@blog.CoverImageUrl">
                            </a>
                            @*內容*@
                            <div class="card-body">
                                <p>
                                    <span>
                                        @*更新時間*@
                                        <small class="mr-1">@blog.UpdateTime</small>
                                    </span>
                                </p>
                                @*標題*@
                                <h4>
                                    <a href="/user/@User.Identity.Name/blog/@blog.Id" class="nav-link text-dark">@blog.Title</a>
                                </h4>
                                @*部分內文*@
                                <p>
                                    <a href="/user/@User.Identity.Name/blog/@blog.Id" class="nav-link text-dark">@blog.PartialContent</a>
                                </p>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
} else {
    <span dir="auto" class="style-scope yt-formatted-string">登入後即可查看你的文章。</span>
}