1.Web/Areas/Back/Controllers/MenuController.cs
using Core.Data.Entities;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Web.Areas.Back.Models;

namespace Web.Areas.Back.Controllers
{
    [Area("Back")]
    public class MenuController : Controller
    {
        public IActionResult Navigation()
        {
            MenuViewModel viewModel = new MenuViewModel
            {
                Menus = GetMenus()
            };
            return PartialView("_Navigation", viewModel);
        }

        private List<Menu> GetMenus()
        {
            List<Menu> result = new List<Menu>();

            Menu menu1 = new Menu()
            {
                Id = 1,
                Name = "權限管理",
                ParentId = -1,
                IsDisable = false,
                Icon = "fas fa-user",
                Sort = 1
            };

            Menu menu2 = new Menu()
            {
                Id = 2,
                Name = "角色權限",
                ParentId = 1,
                IsDisable = false,
                Area = "Back",
                Controller = "RoleController",
                Action = "Index",
                Sort = 2
            };

            Menu menu3 = new Menu()
            {
                Id = 3,
                Name = "帳號管理",
                ParentId = 1,
                IsDisable = false,
                Area = "Back",
                Controller = "AccountController",
                Action = "Index",
                Sort = 1
            };

            result.Add(menu1);
            result.Add(menu2);
            result.Add(menu3);
            return result;
        }
    }
}

1.Web/Views/Shared/_BackLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description" content="Bootstrap Admin App + jQuery">
    <meta name="keywords" content="app, responsive, jquery, bootstrap, dashboard, admin">
    <link rel="icon" type="image/x-icon" href="/favicon.ico">
    <title>@ViewData["Title"] - Web</title>
    <!-- =============== VENDOR STYLES ===============-->
    <!-- FONT AWESOME-->
    <link rel="stylesheet" href="~/vendor/@@fortawesome/fontawesome-free-webfonts/css/fa-brands.css">
    <link rel="stylesheet" href="~/vendor/@@fortawesome/fontawesome-free-webfonts/css/fa-regular.css">
    <link rel="stylesheet" href="~/vendor/@@fortawesome/fontawesome-free-webfonts/css/fa-solid.css">
    <link rel="stylesheet" href="~/vendor/@@fortawesome/fontawesome-free-webfonts/css/fontawesome.css">
    <!-- SIMPLE LINE ICONS-->
    <link rel="stylesheet" href="~/vendor/simple-line-icons/css/simple-line-icons.css">
    <!-- ANIMATE.CSS-->
    <link rel="stylesheet" href="~/vendor/animate.css/animate.css">
    <!-- WHIRL (spinners)-->
    <link rel="stylesheet" href="~/vendor/whirl/dist/whirl.css">
    <!-- =============== PAGE VENDOR STYLES ===============-->
    <!-- =============== BOOTSTRAP STYLES ===============-->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" id="bscss">
    <!-- =============== APP STYLES ===============-->
    <link rel="stylesheet" href="~/css/app.css" id="maincss">
    <link href="~/css/theme-f.css" rel="stylesheet" />
</head>

<body>
    <div class="wrapper">
        <!-- top navbar-->
        <header class="topnavbar-wrapper">
            <!-- START Top Navbar-->
            <nav class="navbar topnavbar">
                <!-- Start 側邊表頭-->
                <div class="navbar-header">
                    <a class="navbar-brand" href="#/">
                        <div class="brand-logo">
                            <img class="img-fluid" src="~/img/logo.png" alt="App Logo">
                        </div>
                        <div class="brand-logo-collapsed">
                            <img class="img-fluid" src="~/img/logo-single.png" alt="App Logo">
                        </div>
                    </a>
                </div>
                <!-- END 側邊表頭-->
                <!-- START 功能Icon(三條線)-->
                <ul class="navbar-nav mr-auto flex-row">
                    <li class="nav-item">
                        <!-- Button used to collapse the left sidebar. Only visible on tablet and desktops-->
                        <a class="nav-link d-none d-md-block d-lg-block d-xl-block" href="#" data-trigger-resize="" data-toggle-state="aside-collapsed">
                            <em class="fas fa-bars"></em>
                        </a>
                        <!-- Button to show/hide the sidebar on mobile. Visible on mobile only.-->
                        <a class="nav-link sidebar-toggle d-md-none" href="#" data-toggle-state="aside-toggled" data-no-persist="true">
                            <em class="fas fa-bars"></em>
                        </a>
                    </li>
                    <!-- START User 資訊-->
                    <li class="nav-item d-none d-md-block">
                        <!-- Button used to collapse the left sidebar. Only visible on tablet and desktops-->
                        <a class="nav-link" id="user-block-toggle" href="#user-block" data-toggle="collapse">
                            <em class="icon-user"></em>
                        </a>
                    </li>
                    <!-- END User 資訊-->
                </ul>
                <!-- END 功能Icon(三條線)-->
                <!-- START Right Navbar-->
                <ul class="navbar-nav flex-row">
                    <!-- Search icon-->
                    <li class="nav-item">
                        <a class="nav-link" href="#" data-search-open="">
                            <em class="icon-magnifier"></em>
                        </a>
                    </li>
                    <!-- START Alert menu-->
                    <li class="nav-item dropdown dropdown-list">
                        <a class="nav-link dropdown-toggle dropdown-toggle-nocaret" href="#" data-toggle="dropdown">
                            <em class="icon-bell"></em>
                            <span class="badge badge-danger">11</span>
                        </a>
                        <!-- START Dropdown menu-->
                        <div class="dropdown-menu dropdown-menu-right animated flipInX">
                            <div class="dropdown-item">
                                <!-- START list group-->
                                <div class="list-group">
                                    <!-- list item-->
                                    <div class="list-group-item list-group-item-action">
                                        <div class="media">
                                            <div class="align-self-start mr-2">
                                                <em class="fab fa-twitter fa-2x text-info"></em>
                                            </div>
                                            <div class="media-body">
                                                <p class="m-0">New followers</p>
                                                <p class="m-0 text-muted text-sm">1 new follower</p>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- list item-->
                                    <div class="list-group-item list-group-item-action">
                                        <div class="media">
                                            <div class="align-self-start mr-2">
                                                <em class="fas fa-envelope fa-2x text-warning"></em>
                                            </div>
                                            <div class="media-body">
                                                <p class="m-0">New e-mails</p>
                                                <p class="m-0 text-muted text-sm">You have 10 new emails</p>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- list item-->
                                    <div class="list-group-item list-group-item-action">
                                        <div class="media">
                                            <div class="align-self-start mr-2">
                                                <em class="fas fa-tasks fa-2x text-success"></em>
                                            </div>
                                            <div class="media-body">
                                                <p class="m-0">Pending Tasks</p>
                                                <p class="m-0 text-muted text-sm">11 pending task</p>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- last list item-->
                                    <div class="list-group-item list-group-item-action">
                                        <span class="d-flex align-items-center">
                                            <span class="text-sm">More notifications</span>
                                            <span class="badge badge-danger ml-auto">14</span>
                                        </span>
                                    </div>
                                </div>
                                <!-- END list group-->
                            </div>
                        </div>
                        <!-- END Dropdown menu-->
                    </li>
                    <!-- END Alert menu-->
                </ul>
                <!-- END Right Navbar-->
                <!-- START Search form-->
                <form class="navbar-form" role="search" action="search.html">
                    <div class="form-group">
                        <input class="form-control" type="text" placeholder="Type and hit enter ...">
                        <div class="fas fa-times navbar-form-close" data-search-dismiss=""></div>
                    </div>
                    <button class="d-none" type="submit">Submit</button>
                </form>
                <!-- END Search form-->
            </nav>
            <!-- END Top Navbar-->
        </header>
        <!-- sidebar-->
        <aside class="aside-container">
            <!-- 側邊選單 (左邊)-->
            <div id="menuDiv" class="aside-inner">

            </div>
            <!-- END 側邊選單 (左邊)-->
        </aside>
        <!-- Main section-->
        <section class="section-container">
            <!-- Page content-->
            <div class="content-wrapper">
                <div class="content-heading">
                    <div>
                        @ViewData["Title"]
                    </div>
                    <!-- START Language list-->
                    <div class="ml-auto">
                        <div class="btn-group">
                            <button class="btn btn-secondary dropdown-toggle dropdown-toggle-nocaret" type="button" data-toggle="dropdown">中文</button>
                            <div class="dropdown-menu dropdown-menu-right-forced animated fadeInUpShort" role="menu">
                                <a class="dropdown-item" href="#" data-set-lang="en">中文</a>
                            </div>
                        </div>
                    </div>
                    <!-- END Language list-->
                </div>
                <div class="row">
                    <div class="col-12 text-center">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </section>
        <!-- Page footer-->
        <footer class="footer-container">
            &copy; 2020 - Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </footer>
    </div>
    <!-- =============== VENDOR SCRIPTS ===============-->
    <!-- MODERNIZR-->
    <script src="~/vendor/modernizr/modernizr.custom.js"></script>
    <!-- JQUERY-->
    <script src="~/vendor/jquery/dist/jquery.js"></script>
    <!-- BOOTSTRAP-->
    <script src="~/vendor/popper.js/dist/umd/popper.js"></script>
    <script src="~/vendor/bootstrap/dist/js/bootstrap.js"></script>
    <!-- STORAGE API-->
    <script src="~/vendor/js-storage/js.storage.js"></script>
    <!-- JQUERY EASING-->
    <script src="~/vendor/jquery.easing/jquery.easing.js"></script>
    <!-- ANIMO-->
    <script src="~/vendor/animo/animo.js"></script>
    <!-- SCREENFULL-->
    <script src="~/vendor/screenfull/dist/screenfull.js"></script>
    <!-- LOCALIZE-->
    <script src="~/vendor/jquery-localize/dist/jquery.localize.js"></script>
    <!-- =============== PAGE VENDOR SCRIPTS ===============-->
    <!-- =============== APP SCRIPTS ===============-->
    <script src="~/js/app.js"></script>
    @RenderSection("Scripts", required: false)

    <script>
        $.ajax({
            url: '@Url.Action("Navigation", "Menu", new { Area = "Back" })',
            success: function (res) {
                $("#menuDiv").html(res);
                //console.log(res)
            }
        })
    </script>

</body>

</html>

1.Web/Views/Shared/_FrontLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <!-- FONT AWESOME-->
    <link rel="stylesheet" href="~/vendor/@@fortawesome/fontawesome-free-webfonts/css/fa-brands.css">
    <link rel="stylesheet" href="~/vendor/@@fortawesome/fontawesome-free-webfonts/css/fa-regular.css">
    <link rel="stylesheet" href="~/vendor/@@fortawesome/fontawesome-free-webfonts/css/fa-solid.css">
    <link rel="stylesheet" href="~/vendor/@@fortawesome/fontawesome-free-webfonts/css/fontawesome.css">
    <!-- SIMPLE LINE ICONS-->
    <link rel="stylesheet" href="~/vendor/simple-line-icons/css/simple-line-icons.css">
    <link href="~/css/coffee.css" rel="stylesheet" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RJG Blog</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">文章列表</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">未開放</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Introduce">介紹</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Back" asp-controller="Home" asp-action="Index">後台管理</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Web - Blog
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Include the Dark theme -->
    <link rel="stylesheet" href="~/vendor/@@sweetalert2/theme-dark/dark.css">
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@@10"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

1.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>